/**
 * Replace ID-Selectors with corresponding Attribute-Selectors.
 */

module.exports = (function() {

	/**
	 * HTML 4 Spec:
	 * ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by 
	 * any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").
	 * Colons and periods are ignored because as they seem not working in a variety of browsers, 
	 * CSS editors, and JavaScript frameworks.
	 */

	var CSSID = /(#)([A-Za-z][A-Za-z0-9_\-]+)/g;

	/**
	 * Return function invoked by Rework 
	 * @param {Object} style Style object generated by Rework
	 */

	return function(style) {

		/**
		 * Iterate over rules of stylesheet string
		 */

		style.rules.forEach(function (rule){

			/**
			* Replacing the selectors array of a single rule with
			* an array in which the selectors that include
			* Ids are altered to use attribute-selectors
			*/
			
			if ( !rule.selectors ) {
				return;
			}

			rule.selectors = rule.selectors.map(function(selector){
				
				return selector.replace(CSSID, '[id="$2"]');

			});

		});

	};

})();